"""initial domain model

Revision ID: fc060ed3957d
Revises: 
Create Date: 2026-09-29 12:01:22.279848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc060ed3957d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_definitions',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('capabilities', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('allowed_tools', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('preferred_model_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('permissions', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='agent_definition_risk_level'), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'DEPRECATED', name='agent_definition_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('missions',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PLANNING', 'ASSEMBLING', 'RUNNING', 'WAITING_APPROVAL', 'VERIFYING', 'COMPLETED', 'FAILED', 'CANCELLED', name='mission_status'), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('success_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_definitions',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('capabilities', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('authentication_type', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='tool_definition_risk_level'), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'NOT_CONFIGURED', 'DISABLED', 'FAILED', name='tool_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('decisions',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('evidence_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='decision_risk_level'), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'APPROVED', 'REJECTED', 'SUPERSEDED', name='decision_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_mission_id'), 'decisions', ['mission_id'], unique=False)
    op.create_table('tasks',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'ASSIGNED', 'RUNNING', 'WAITING_APPROVAL', 'COMPLETED', 'FAILED', 'CANCELLED', name='task_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='task_priority'), nullable=False),
    sa.Column('required_capabilities', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('dependencies', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('assigned_agent', sa.UUID(), nullable=True),
    sa.Column('tool_requirements', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('actual_output', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent'], ['agent_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_mission_id'), 'tasks', ['mission_id'], unique=False)
    op.create_table('verification_reports',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('verification_status', sa.Enum('PASSED', 'FAILED', 'PARTIAL', name='verification_status'), nullable=False),
    sa.Column('criteria_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_reports_mission_id'), 'verification_reports', ['mission_id'], unique=False)
    op.create_table('agent_executions',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('agent_definition_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='agent_execution_status'), nullable=False),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_definition_id'], ['agent_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_executions_agent_definition_id'), 'agent_executions', ['agent_definition_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_mission_id'), 'agent_executions', ['mission_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_task_id'), 'agent_executions', ['task_id'], unique=False)
    op.create_table('approvals',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'MODIFIED', name='approval_status'), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_decision_id'), 'approvals', ['decision_id'], unique=False)
    op.create_index(op.f('ix_approvals_mission_id'), 'approvals', ['mission_id'], unique=False)
    op.create_table('conflicts',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=True),
    sa.Column('detected_by', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('original_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conflicting_evidence_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DETECTED', 'UNDER_REVIEW', 'RESOLVED', 'ESCALATED', name='conflict_status'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflicts_decision_id'), 'conflicts', ['decision_id'], unique=False)
    op.create_index(op.f('ix_conflicts_mission_id'), 'conflicts', ['mission_id'], unique=False)
    op.create_table('evidence',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('agent_execution_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_execution_id'], ['agent_executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_agent_execution_id'), 'evidence', ['agent_execution_id'], unique=False)
    op.create_index(op.f('ix_evidence_mission_id'), 'evidence', ['mission_id'], unique=False)
    op.create_index(op.f('ix_evidence_task_id'), 'evidence', ['task_id'], unique=False)
    op.create_table('execution_events',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('agent_execution_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('MISSION_CREATED', 'MISSION_PLANNED', 'AGENT_SELECTED', 'AGENT_STARTED', 'AGENT_MESSAGE', 'TOOL_SELECTED', 'TOOL_CALLED', 'TOOL_RESULT', 'EVIDENCE_CREATED', 'DECISION_CREATED', 'APPROVAL_REQUESTED', 'APPROVAL_GRANTED', 'APPROVAL_REJECTED', 'TASK_FAILED', 'TASK_REPLANNED', 'VERIFICATION_STARTED', 'MISSION_COMPLETED', name='execution_event_type'), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILURE', 'IN_PROGRESS', name='execution_event_status'), nullable=False),
    sa.Column('error_category', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_execution_id'], ['agent_executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_events_agent_execution_id'), 'execution_events', ['agent_execution_id'], unique=False)
    op.create_index(op.f('ix_execution_events_correlation_id'), 'execution_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_execution_events_event_type'), 'execution_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_execution_events_mission_id'), 'execution_events', ['mission_id'], unique=False)
    op.create_index(op.f('ix_execution_events_task_id'), 'execution_events', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_events_task_id'), table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_mission_id'), table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_event_type'), table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_correlation_id'), table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_agent_execution_id'), table_name='execution_events')
    op.drop_table('execution_events')
    op.drop_index(op.f('ix_evidence_task_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_mission_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_agent_execution_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_conflicts_mission_id'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_decision_id'), table_name='conflicts')
    op.drop_table('conflicts')
    op.drop_index(op.f('ix_approvals_mission_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_decision_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_agent_executions_task_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_mission_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_agent_definition_id'), table_name='agent_executions')
    op.drop_table('agent_executions')
    op.drop_index(op.f('ix_verification_reports_mission_id'), table_name='verification_reports')
    op.drop_table('verification_reports')
    op.drop_index(op.f('ix_tasks_mission_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_decisions_mission_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_table('tool_definitions')
    op.drop_table('missions')
    op.drop_table('agent_definitions')
    # ### end Alembic commands ###
